import type { CandleKind, CharId, MapId, PowerKind, RegimeId } from './config.js';

/* ── world ─────────────────────────────────────────────────────────────────── */

export interface Candle {
  /** Monotonic generation index. Stable identity across culling and serialisation. */
  i: number;
  x: number;
  /** Top edge, y grows downward. */
  y: number;
  w: number;
  kind: CandleKind;
  bodyH: number;
  /** Has this candle already been counted toward `cleared`. */
  scored: boolean;
  /** True when this candle sits one pitch past a gap. Diagnostics + renderer only. */
  gapped: boolean;
  /** True on the first doji of a trend-change bridge — the candle you are meant to flip on. */
  bridgeStart: boolean;
}

export interface Pip {
  i: number;
  x: number;
  y: number;
  got: boolean;
}

export interface Power {
  i: number;
  x: number;
  y: number;
  kind: PowerKind;
  got: boolean;
}

/* ── player ────────────────────────────────────────────────────────────────── */

export interface PlayerState {
  x: number;
  y: number;
  vy: number;
  ground: boolean;
  jumps: number;
  /** Coyote time remaining, seconds. */
  coy: number;
  /** Jump buffer remaining, seconds. */
  buf: number;
  short: boolean;
  /** Flip cooldown, seconds. */
  flipCd: number;
  alive: boolean;
  /** Index of the candle being stood on, or -1. Never pulled out from under the player. */
  standIdx: number;
  /** Index of the last candle landed on, or -1. Prevents double-scoring a landing. */
  lastLandIdx: number;
}

export interface Buffs {
  /** Leverage seconds remaining — 2x P&L. */
  lev: number;
  /** Momentum seconds remaining — auto-flight above the tape. */
  bull: number;
  /** Stop loss armed — one free save from a fall. */
  shield: boolean;
}

/* ── session ───────────────────────────────────────────────────────────────── */

export type SimMode = 'attract' | 'running' | 'levelBreak' | 'reviveOffer' | 'ended';
/** `cleared` means every level was survived — the top of the ladder. */
export type EndReason = 'cleared' | 'liquidated' | 'declined';

/**
 * Everything needed to reproduce a session bit for bit.
 *
 * `seed` is generated by the server and never chosen by the client. `handicap` is the
 * player's persisted adaptive-difficulty scalar; it is issued with the session for the
 * same reason the seed is — it feeds the speed ramp, so a client-held value would let a
 * client slow the game down.
 */
export interface SessionConfig {
  seed: number;
  mapId: MapId;
  charId: CharId;
  /** 0..1, dampens the speed ramp for players who keep dying early. */
  handicap: number;
  engineVersion: number;
}

/* ── inputs ────────────────────────────────────────────────────────────────── */

export const IN = {
  JUMP_DOWN: 0,
  JUMP_UP: 1,
  FLIP: 2,
  REVIVE: 3,
  DECLINE: 4,
  /** Dismiss the level-clear panel and start the next level. */
  CONTINUE: 5,
} as const;

export type InputCode = (typeof IN)[keyof typeof IN];

/** `[frame, code]`. Compact on the wire; a full session is a few KB. */
export type InputEvent = readonly [frame: number, code: number];
export type InputTape = readonly InputEvent[];

export const INPUT_CODES: readonly number[] = Object.values(IN);

/* ── events (renderer/audio only — never read back into the sim) ───────────── */

export type SimEvent =
  | { t: 'jump'; first: boolean; x: number; y: number }
  | { t: 'land'; x: number; y: number; kind: CandleKind; perfect: boolean; perfectRun: number }
  | { t: 'streak'; mult: number }
  | { t: 'flip'; short: boolean; clean: boolean; x: number; y: number }
  | { t: 'pip'; x: number; y: number; n: number }
  | { t: 'power'; kind: PowerKind; x: number; y: number }
  | { t: 'stumble'; x: number; y: number; mult: number }
  | { t: 'shield'; x: number; y: number }
  | { t: 'bell' }
  | { t: 'levelClear'; level: number; pnl: number; candles: number }
  | { t: 'levelStart'; level: number }
  | { t: 'regime'; name: string; id: RegimeId }
  | { t: 'death'; x: number; y: number }
  | { t: 'reviveOffer' }
  | { t: 'revive' }
  | { t: 'end'; reason: EndReason };

/* ── snapshot handed to the renderer ───────────────────────────────────────── */

export type Deep<T> = { readonly [K in keyof T]: T[K] extends object ? Deep<T[K]> : T[K] };

export interface SimSnapshot {
  frame: number;
  mode: SimMode;
  endReason: EndReason | null;
  /** Seconds of simulated time since session start. Never wall clock. */
  t: number;
  cam: number;
  spd: number;
  /** Seconds left in the current level. */
  left: number;
  /** 1-based level the player is on. */
  level: number;
  /** Seconds left on the level-clear panel before it continues by itself. */
  breakLeft: number;
  pnl: number;
  pips: number;
  mult: number;
  bestMult: number;
  streak: number;
  perfect: number;
  perfectRun: number;
  cleared: number;
  flips: number;
  cleanFlips: number;
  belled: boolean;
  /** 0..1 progress through the session; drives the sky gradient. */
  dayP: number;
  slow: number;
  inv: number;
  regime: RegimeId;
  usedRevive: boolean;
  reviveLeft: number;
  player: PlayerState;
  buffs: Buffs;
  candles: Candle[];
  pipsList: Pip[];
  powers: Power[];
}

/* ── replay ────────────────────────────────────────────────────────────────── */

export type ReplayErrorCode =
  | 'ENGINE_VERSION_MISMATCH'
  | 'TAPE_TOO_LONG'
  | 'FRAME_OUT_OF_RANGE'
  | 'FRAME_NOT_MONOTONIC'
  | 'UNKNOWN_INPUT_CODE'
  | 'INPUT_RATE_EXCEEDED'
  | 'INPUT_AFTER_END'
  | 'BAD_CONFIG';

export interface ReplayResult {
  ok: boolean;
  error?: ReplayErrorCode;
  errorDetail?: string;
  /** Server-authoritative score. The only number that may ever touch the ledger. */
  score: number;
  candles: number;
  bestMult: number;
  cleanFlips: number;
  flips: number;
  pips: number;
  /** Highest level reached. */
  level: number;
  frames: number;
  endReason: EndReason | null;
  /** Stddev of inter-press gaps in ms. Low = suspiciously frame-perfect. Flag, never ban. */
  inputJitterMs: number;
  inputCount: number;
  /** Final-state fingerprint. Compare across environments to catch determinism drift. */
  digest: string;
}
